name = "sequence-arena"
main = "worker.js"
compatibility_date = "2026-09-26"

[[d1_databases]]
binding = "SEQUENCE_ARENA"
database_name = "sequence-arena"
database_id = "2f8489e5-b60c-4cbc-9f99-14440192a136"
